[package]
name = "blog-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
dotenvy = "0.15.7"
sqlx = "0.8.6"
time = {version =  "0.3.47",features = ["macros"] }
tokio = { version = "1.49.0",features = ["rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["json", "env-filter", "local-time"] }
